name: CI/ CD Pipeline
"on":
  push:
    branches:
      - main

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4

#      - name: Run tests
#        run: make unit-test

  version:
    uses: "warnermediacode/reusable-workflows/.github/workflows/versions.yml@main"
       
    
  dev-app: 
    needs: version
    uses: "warnermediacode/reusable-workflows/.github/workflows/build-retag-deploy.yml@main"
    with: 
      ENV: dev
      AWS_ASSUME_ROLE: ${{ vars.AWS_ASSUME_ROLE_NONPROD }}
      TIER: app
      VERSION_TAG: ${{ needs.version.outputs.version }}
    
  stage-app: 
    needs: [dev-app, version]
    uses: "warnermediacode/reusable-workflows/.github/workflows/sports-build-and-deploy.yml@main"
    with: 
      ENV: stage
      AWS_ASSUME_ROLE: ${{ vars.AWS_ASSUME_ROLE_NONPROD }}
      TIER: app
      VERSION_TAG: ${{ needs.version.outputs.version }}

      
  
